In [2]:
import pandas as pd
import numpy as np
import sklearn
import sklearn.model_selection as skl
import matplotlib.pyplot as plt
import json

df = pd.read_csv('../datasets/SpotifyAudioFeatures-full.csv')

data_X = df.drop(['popularity'], axis = 1)
data_Y = df['popularity']

df.head()


Unnamed: 0   artist_name                                track_name  \
0           0   Post Malone                                   Circles   
1           1  Travis Scott                       HIGHEST IN THE ROOM   
2           2    Juice WRLD  Bandit (with YoungBoy Never Broke Again)   
3           3  Selena Gomez                       Lose You To Love Me   
4           4     blackbear                           hot girl bummer   

                 track_id  popularity  num_artists  release_month  \
0  21jGcNKet2qwijlDFuPiPb          99            1              9   
1  3eekarcy7kvN4yt5ZFzltW          98            1             10   
2  6Gg1gjgKi2AK4e0qzsR7sd          94            2             10   
3  1HfMVBKM75vxSfsQ5VefZ5          99            1             10   
4  7aiClxsDWFRQ0Kzk5KI5ku          97            1              8   

   release_weekday  danceability  energy  ...  speechiness  acousticness  \
0                5         0.695   0.762  ...       0.0395        0.1920   
1                5         0.598   0.427  ...       0.0317        0.0546   
2                5         0.474   0.631  ...       0.3430        0.0687   
3                3         0.505   0.340  ...       0.0438        0.5760   
4                5         0.778   0.559  ...       0.0776        0.1280   

   instrumentalness  liveness  valence    tempo  duration_ms  time_signature  \
0          0.002440    0.0863   0.5530  120.042       215280               4   
1          0.000006    0.2100   0.0605   76.469       175721               4   
2          0.000000    0.1320   0.4250  180.051       189323               4   
3          0.000000    0.2100   0.0916  101.993       206459               4   
4          0.000000    0.3990   0.6780  129.989       185093               1   

   track_len  artist_len  
0          7          11  
1         19          12  
2         40          10  
3         19          12  
4         15           9  

[5 rows x 23 columns]

In [21]:
Xn = pd.get_dummies(data_X) # All numerical to categorical
Xn.head()

Unnamed: 0  num_artists  release_month  release_weekday  danceability  \
0           0            1              9                5         0.695   
1           1            1             10                5         0.598   
2           2            2             10                5         0.474   
3           3            1             10                3         0.505   
4           4            1              8                5         0.778   

   energy  key  loudness  mode  speechiness  ...  \
0   0.762    0    -3.497     1       0.0395  ...   
1   0.427    7    -8.764     0       0.0317  ...   
2   0.631    5    -5.884     0       0.3430  ...   
3   0.340    4    -9.005     1       0.0438  ...   
4   0.559    6    -7.109     0       0.0776  ...   

   track_id_7zOWMvYYVmAj5k1NoXNurV  track_id_7zOi7qCwJPaZRXHcuOJSTm  \
0                                0                                0   
1                                0                                0   
2                                0                                0   
3                                0                                0   
4                                0                                0   

   track_id_7zS5nYL2hL7eU1BnDEer9K  track_id_7zTTDkkLkJ2iHAqq1daDCr  \
0                                0                                0   
1                                0                                0   
2                                0                                0   
3                                0                                0   
4                                0                                0   

   track_id_7zZTXP1SZWituBpo0AgxkY  track_id_7zg21FcHyzgMMo6OlXjtBC  \
0                                0                                0   
1                                0                                0   
2                                0                                0   
3                                0                                0   
4                                0                                0   

   track_id_7zmUna3f0xGY0vFDTa7aks  track_id_7zpMz3am0n83WmDxVqp9GQ  \
0                                0                                0   
1                                0                                0   
2                                0                                0   
3                                0                                0   
4                                0                                0   

   track_id_7zqMpOFj0pkIs2o8SF1AyR  track_id_7zqwamMJnDIy16rON2DUCG  
0                                0                                0  
1                                0                                0  
2                                0                                0  
3                                0                                0  
4                                0                                0  

[5 rows x 21090 columns]

In [27]:
# Separate training to test. We shuffle to desorder the data
from sklearn.utils import shuffle
Xn, Y = shuffle(Xn, data_Y)

(x_train, x_test, y_train, y_test) = skl.train_test_split(Xn, Y, test_size=0.33)

In [25]:
from sklearn.naive_bayes import BernoulliNB # For binary features (every variables)
from statsmodels.stats.proportion

model = BernoulliNB()
# confusion_matrix
# classification_report

SyntaxError: invalid syntax (<ipython-input-25-58bb5e05a641>, line 2)

In [26]:
scores = sklearn.model_selection.cross_val_score(model, Xn, Y, cv=10)

NameError: name 'model' is not defined

In [30]:
# Decision tree
from sklearn import tree 

clf = tree.DecisionTreeClassifier(criterion='entropy')
pred = clf.fit(x_train, y_train).predict(x_test)
print(f'{sklearn.metrics.confusion_matrix(y_test, pred)}\n')
print(f'Accuracy on test set: {sklearn.metrics.accuracy_score(y_test, pred)}\n')
print(sklearn.metrics.classification_report(y_test, pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Accuracy on test set: 0.032435939020434644

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        17
           2       0.00      0.00      0.00        10
           3       0.08      0.11      0.09        19
           4       0.00      0.00      0.00        15
           5       0.00      0.00      0.00        17
           6       0.00      0.00      0.00        15
           7       0.00      0.00      0.00         8
           8       0.00      0.00      0.00        16
           9       0.00      0.00      0.00         6
          10       0.00      0.00      0.00        13
          11       0.03      0.06      0.04        16
          12       0.00      0.00      0.00        32
          13       0.00      0.00      0.00        20
          14       0.00      0.00      0.00        21
          15       0.00 

/home/felipe/.local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/felipe/.local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
